version: '3.8'
services:
  pg:
    image: 'postgres:alpine'
    container_name: 'shorty_db'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'shorty'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'pg:/var/lib/postgresql/data'
    networks:
      - default
    restart: 'always'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: 'shorty_web'
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@shorty_db:5432/shorty'
    build:
      context: .
      dockerfile: 'Dockerfile'
    networks:
      - default
    ports:
      - '3001:3001'
    depends_on:
      pg:
        condition: service_healthy

networks:
  default:

volumes:
  pg:
