name: Tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Deps
        run: yarn install --frozen-lockfile
      
      - name: Start services
        run: yarn docker:start
      
      - name: Run Cypress Tests
        run: yarn cypress:run

  rtl_tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install deps
        run: yarn install --frozen-lockfile
        
      - name: Run tests
        run: yarn test
